# Generated by Django 3.1.4 on 2021-01-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('data_nascimento', models.CharField(default='', max_length=10)),
                ('grupo_de_risco', models.BooleanField(default=False, max_length=255)),
                ('telefone', models.CharField(default='91999999999', max_length=255)),
                ('url_img', models.CharField(default='img.jpg', max_length=255)),
                ('email', models.CharField(default='contato@email.com', max_length=255)),
                ('senha', models.CharField(default='PADRAO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(default='91999999999', max_length=255)),
                ('url_img', models.CharField(default='img.jpg', max_length=255)),
                ('email', models.CharField(default='contato@email.com', max_length=255)),
                ('senha', models.CharField(default='PADRAO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('crm', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.CharField(default='', max_length=10)),
                ('telefone', models.CharField(default='91999999999', max_length=255)),
                ('url_img', models.CharField(default='img.jpg', max_length=255)),
                ('email', models.CharField(default='contato@email.com', max_length=255)),
                ('senha', models.CharField(default='PADRAO', max_length=20)),
                ('especialidade', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapi.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_consulta', models.CharField(max_length=255)),
                ('data', models.CharField(default='', max_length=10)),
                ('hora', models.CharField(default='', max_length=5)),
                ('tipo_consulta', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('DOMICILIO', 'Domicilio')], default='PRESENCIAL', max_length=20)),
                ('cliente_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.cliente')),
                ('clinica_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.clinica')),
                ('medico_crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.medico')),
            ],
        ),
    ]
