# Generated by Django 3.1.4 on 2020-12-29 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_clinica_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo_de_risco',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='cnpj',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medico',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_consulta', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField()),
                ('tipo_consulta', models.CharField(max_length=255)),
                ('clinica_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.clinica')),
                ('clinte_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.cliente')),
                ('medico_crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.medico')),
            ],
        ),
    ]
