# Generated by Django 3.1.4 on 2020-12-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20201229_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='clinte_cpf',
            new_name='cliente_cpf',
        ),
    ]
