# Generated by Django 3.1.4 on 2020-12-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20201229_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='are_atuacao',
            new_name='area_atuacao',
        ),
    ]
