# Generated by Django 3.1.4 on 2020-12-03 02:45

from django.db import migrations

def create_data(apps, schema_editor):
        Customer = apps.get_model('usuarios', 'Clientes')
        Customer(first_name="Customer 001", last_name="Customer 001", email="customer001@email.com", phone="00000000", address="Customer 000 Address", description= "Customer 001 description").save()



class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
    
    